import type * as cdk from 'aws-cdk-lib';
import type { IConstruct } from 'constructs';
import { NagSuppressions } from 'cdk-nag';

/**
 * Shared, justified cdk-nag suppressions. Every suppression carries a reason; anything not listed here or next to
 * the resource it applies to fails `pnpm --filter @selloeasy/infra synth:check`.
 */

/** Findings on ECS task definitions + their roles for backend containers (api / worker / migrate). */
export function suppressBackendTaskFindings(taskDefinition: IConstruct) {
  NagSuppressions.addResourceSuppressions(
    taskDefinition,
    [
      {
        id: 'AwsSolutions-ECS2',
        reason:
          'Only non-secret configuration is passed as plain environment variables; credentials come from ECS `secrets` ' +
          '(RDS/Redis) or are loaded from Secrets Manager at boot (SECRETS_SOURCE=aws-secrets-manager).',
      },
      {
        id: 'AwsSolutions-IAM5',
        reason:
          'Task role is scoped to the uploads bucket prefix orgs/* (object-level wildcard by design), its KMS key ' +
          '(GenerateDataKey*/ReEncrypt* action families emitted by bucket.grantReadWrite) and the SES mail-domain identity.',
        appliesTo: [
          { regex: '/^Action::s3:.*\\*$/' },
          { regex: '/^Action::kms:.*\\*$/' },
          { regex: '/^Resource::.*orgs/\\*.*$/' },
          { regex: '/^Resource::arn:.*:ses:.*:identity/\\*@.*$/' },
        ],
      },
      {
        id: 'AwsSolutions-IAM5',
        reason:
          'ECS task execution role: ecr:GetAuthorizationToken and CloudWatch Logs stream actions are generated by CDK.',
        appliesTo: ['Resource::*'],
      },
    ],
    true,
  );
}

/** Findings raised on CDK-managed helper Lambdas (log retention, auto-delete objects, cross-region SSM readers). */
export function suppressCdkInternals(stack: cdk.Stack) {
  NagSuppressions.addStackSuppressions(stack, [
    {
      id: 'AwsSolutions-IAM4',
      reason:
        'CDK-managed helper Lambdas (LogRetention / AutoDeleteObjects / cross-region references) use AWSLambdaBasicExecutionRole.',
      appliesTo: ['Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'],
    },
    {
      id: 'AwsSolutions-L1',
      reason: 'Runtime of CDK-managed helper Lambdas is controlled by aws-cdk-lib, not by this app.',
    },
  ]);
  // The LogRetention helper needs logs:PutRetentionPolicy/DeleteRetentionPolicy on "*" (CDK generated).
  for (const child of stack.node.children) {
    if (/^LogRetention[0-9a-f]+$/.test(child.node.id)) {
      NagSuppressions.addResourceSuppressions(
        child,
        [{ id: 'AwsSolutions-IAM5', reason: 'CDK LogRetention helper sets retention on log groups it does not know at synth time.', appliesTo: ['Resource::*'] }],
        true,
      );
    }
  }
}
