import * as cdk from 'aws-cdk-lib';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import { NagSuppressions } from 'cdk-nag';
import type { Construct } from 'constructs';
import type { InfraConfig } from './config';

export interface SecretsStackProps extends cdk.StackProps {
  cfg: InfraConfig;
}

/** JSON keys in `selloeasy/<env>/app` written by `infra/scripts/deploy.sh` and loaded by the app at boot. */
export const APP_SECRET_KEYS = [
  'OPENROUTER_API_KEY',
  'OPENAI_API_KEY',
  'ANTHROPIC_API_KEY',
  'JWT_ACCESS_SECRET',
  'JWT_REFRESH_SECRET',
  'SUPERADMIN_PASSWORD',
] as const;
/** Generated by CloudFormation on create; shared by CloudFront (custom origin header) and the ALB listener rules. */
export const ORIGIN_VERIFY_KEY = 'ORIGIN_VERIFY_TOKEN';

/**
 * Secrets — the app JSON secret `selloeasy/<env>/app` (plan §23.1).
 *
 * Only the ORIGIN_VERIFY_TOKEN is generated here; application values are *never* in the template — the deploy script
 * merges them in with `aws secretsmanager put-secret-value` (existing values, e.g. JWT secrets, are preserved).
 */
export class SecretsStack extends cdk.Stack {
  readonly appSecret: secretsmanager.Secret;

  constructor(scope: Construct, id: string, props: SecretsStackProps) {
    super(scope, id, props);
    const { cfg } = props;

    this.appSecret = new secretsmanager.Secret(this, 'AppSecret', {
      secretName: cfg.appSecretName,
      description: `SelloEasy ${cfg.DEPLOY_ENV} runtime secrets (${APP_SECRET_KEYS.join(', ')}) — populated by infra/scripts/deploy.sh`,
      generateSecretString: {
        secretStringTemplate: JSON.stringify({}),
        generateStringKey: ORIGIN_VERIFY_KEY,
        excludePunctuation: true,
        passwordLength: 48,
      },
      removalPolicy: cfg.isProduction ? cdk.RemovalPolicy.RETAIN : cdk.RemovalPolicy.DESTROY,
    });

    new cdk.CfnOutput(this, 'AppSecretArn', { value: this.appSecret.secretArn });
    new cdk.CfnOutput(this, 'AppSecretName', { value: cfg.appSecretName });

    NagSuppressions.addResourceSuppressions(this.appSecret, [
      {
        id: 'AwsSolutions-SMG4',
        reason:
          'Values are operator-managed (OpenRouter key, JWT secrets). Rotation = re-run deploy.sh with new values; ' +
          'automatic rotation would invalidate sessions without a coordinated redeploy.',
      },
    ]);
  }
}
